// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlrYz1H1SejRdXtULI8WHn83GmuBAMdfA',
    appId: '1:1088704205561:web:9bd67d1298eeb2ea970828',
    messagingSenderId: '1088704205561',
    projectId: 'zakio-2e280',
    authDomain: 'zakio-2e280.firebaseapp.com',
    storageBucket: 'zakio-2e280.firebasestorage.app',
    measurementId: 'G-TXM2BV4M1Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwuBYIzD0iEVvWGKxpJ5ksfxR7aUOYkYM',
    appId: '1:1088704205561:android:d7e5de9efca98523970828',
    messagingSenderId: '1088704205561',
    projectId: 'zakio-2e280',
    storageBucket: 'zakio-2e280.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJn_scb98aRgVSFV4Oo9EcI7fiVOi34oo',
    appId: '1:1088704205561:ios:7f7ca4ee521f5b06970828',
    messagingSenderId: '1088704205561',
    projectId: 'zakio-2e280',
    storageBucket: 'zakio-2e280.firebasestorage.app',
    iosBundleId: 'com.megz.zakio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJn_scb98aRgVSFV4Oo9EcI7fiVOi34oo',
    appId: '1:1088704205561:ios:7f7ca4ee521f5b06970828',
    messagingSenderId: '1088704205561',
    projectId: 'zakio-2e280',
    storageBucket: 'zakio-2e280.firebasestorage.app',
    iosBundleId: 'com.megz.zakio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlrYz1H1SejRdXtULI8WHn83GmuBAMdfA',
    appId: '1:1088704205561:web:4f547aef7e7772ee970828',
    messagingSenderId: '1088704205561',
    projectId: 'zakio-2e280',
    authDomain: 'zakio-2e280.firebaseapp.com',
    storageBucket: 'zakio-2e280.firebasestorage.app',
    measurementId: 'G-E61GLT8C99',
  );
}
